Added table captions
10up/wp-component-library pull request #236
Opened 2020-04-02 18:07 UTC by smy315

https://github.com/10up/wp-component-library/issues/234

2020-04-29 12:40 UTC, timwright12 requested changes
@smy315 instead of moving the heading into a caption, can we keep the headings and create a descriptive content for the captions? I'd like to maintain the headings as screenreader navigable items

2020-07-14 04:08 UTC, jeffpaul commented
@smy315 any updates from the feedback in @timwright12's review?

2020-09-03 11:31 UTC, smy315 commented
@timwright12 PR has been updated. Reverted all the headings and provided descriptive content for the table captions.

2020-09-03 13:35 UTC, timwright12 approved these changes

2020-09-03 13:35 UTC, merged